version: "3.7"
services:
  matomo:
    container_name: matomo
    image: matomo
    environment:
      - MATOMO_DATABASE_HOST=matomo_db
    env_file:
      - ./.env
    depends_on:
      - matomo_db
    restart: unless-stopped
    networks:
      caddy:
      matomo:

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 8090:80
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www/html

    networks:
      caddy:
      matomo:
    labels:
      caddy: matomo.local
      caddy.reverse_proxy: "{{upstreams 80}}"

  matomo_db:
    container_name: matomo_db
    image: mariadb
    command: --max-allowed-packet=64MB
    environment:
      - MYSQL_ROOT_PASSWORD=inventa96
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      matomo:

volumes:
  data:
    driver: local

networks:
  matomo:
  caddy:
    external: true
